platform:
  - x86
  - x64
      
install:
 - dir "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin"
 - type "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" 
 - ps: Invoke-WebRequest -Uri "https://files.pythonhosted.org/packages/fa/a5/20e320701292364fa6d1f99a76ae75119d31ee2c8f168637cef8ffc5a977/lupa-1.6.tar.gz" -OutFile lupa-1.6.tar.gz
 - ps: 7z e lupa-1.6.tar.gz
 - ps: 7z x lupa-1.6.tar
 
 - ps: Invoke-WebRequest -Uri "http://luajit.org/download/LuaJIT-2.0.5.tar.gz" -OutFile LuaJIT-2.0.5.tar.gz
 - ps: 7z e LuaJIT-2.0.5.tar.gz
 - ps: 7z x LuaJIT.2.0.5.tar -o"lupa-1.6"

build_script:
  - cd lupa-1.6

  - cd LuaJIT-2.0.5\src
  - call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat"
  - setenv /release /"%platform%"
  - msvcbuild.bat
  - cd ..\..
  
  - pip install cibuildwheel==0.9.4
  - if "%platform%" EQU "x86" ( set CIBW_SKIP="*-win_amd64" )
  - if "%platform%" EQU "x64" ( set CIBW_SKIP="*-win32" )
  - echo CIBW_SKIP=%CIBW_SKIP%
  - cibuildwheel --output-dir %APPVEYOR_BUILD_FOLDER%\wheelhouse
artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels

deploy:
  release: lupa-wheels-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: Mg6hwOigPz3G3y//LToGND67Vbp1kKRJu6grZbiJAOlRGcN/jVIFI3ePKXJySYh+
  on:
    branch: master                 # release from master branch only
